# Generated by Django 6.0.4 on 2026-05-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensaje",
            name="rol",
            field=models.CharField(
                choices=[("User", "Usuario"), ("asistant", "Asistente")], max_length=20
            ),
        ),
    ]
