# Generated by Django 6.0.4 on 2026-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_mensaje_rol"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversacion",
            old_name="Usuario",
            new_name="usuario",
        ),
        migrations.AlterField(
            model_name="mensaje",
            name="rol",
            field=models.CharField(
                choices=[("User", "Usuario"), ("assistant", "Asistente")], max_length=20
            ),
        ),
    ]
